Glava2
Kseelina/POIP_Kersovow pull request #5
Opened 2023-04-22 12:36 UTC by Kseelina

2023-04-22 12:45 UTC, lamer0k commented on Kursovow.adoc
> +- 0: прерывистое режим инжектированных каналов отключены
не по русски. Прерывистый лучше заменить, на одиничный.

2023-04-22 12:46 UTC, lamer0k commented on Kursovow.adoc
> +- *1: прерывистое режим инжектированных каналов включены*
тоже самое.

2023-04-22 12:47 UTC, lamer0k commented on Kursovow.adoc
> +. Измерение температуры при помощи АЦП и складывание полученных
и сохранение

2023-04-22 12:48 UTC, lamer0k commented on Kursovow.adoc
> +- 0: часы TIM1 отключены +
что за часы? Таймер  выключен.

2023-04-22 12:48 UTC, lamer0k commented on Kursovow.adoc
> +- *1: часы TIM1 включены* +
таймер включен.

2023-04-22 12:49 UTC, lamer0k commented on Kursovow.adoc
> +- *0: Счетчик используется в качестве счетчика*
:) прямой счет счетчика.

2023-04-22 12:49 UTC, lamer0k commented on Kursovow.adoc
> +- 1: Счетчик используется как обратный счетчик +
обратный счет...

2023-04-22 12:51 UTC, lamer0k commented on Kursovow.adoc
> +- *1: Вкл. - сигнал OC4 выводится на соответствующий выходной контакт*
контакт мы вроде ножка процессора называем. И почему СС4, а не 1 скажем?? Ножка процессора какая будет?

2023-04-22 12:54 UTC, lamer0k commented on Kursovow.adoc
> +- 0: Захват отключен
Почему захват? Ты же его для задания используешь, он до этого значения будет считать, это наоборот же сравнение. Захват используется, чтобы померить например частоту с раходомера. Там да будет захват. Пришел импульс, мы пошли в таймер и узнали при до скольки таймер посчитал.

2023-04-22 12:58 UTC, lamer0k commented on Kursovow.adoc
> +class IMeasureParameter
Почти норм... 
1. функция должна быть абстрактной, каждый конкретный параметр, будет её переобределять и расчитывать по своим формулам.
2. Интерфейс сюда по всем никем не юзается :)

2023-04-29 12:03 UTC, Kseelina commented on Kursovow.adoc
> +- *1: Вкл. - сигнал OC4 выводится на соответствующий выходной контакт*
я вверху писала что ножка PA11 используется и что буду использовать 4 канал таймера 1, или надо обязательно по порядку их использовать?

2023-04-29 12:07 UTC, lamer0k commented
Привет, сейчас в 17:30 сделаю щанятие5:04 PM, 29 апреля 2023 г., Kseelina ***@***.***>:
@Kseelina commented on this pull request.



In Kursovow.adoc:
> @@ -595,15 +596,15 @@ image::TIM1_CCER.png[]
 Бит 12 CC4E: выход захвата/сравнения 1 включен.
 *Канал CC4 настроен как выход:*
 
- - 0: Выкл. — OC4 не активен
- - *1: Вкл. - сигнал OC4 выводится на соответствующий выходной контакт*
+- 0: Выкл. — OC4 не активен
+- *1: Вкл. - сигнал OC4 выводится на соответствующий выходной контакт*

я вверху писала что ножка PA11 используется и что буду использовать 4 канал таймера 1, или надо обязательно по порядку их использовать?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

2023-04-29 12:51 UTC, Kseelina commented on Kursovow.adoc
> +Бит 12 JDISCEN: включает/отключает одиночный режим инжектированных каналов
Исправила

2023-04-29 12:52 UTC, Kseelina commented on Kursovow.adoc
> +. Измерение температуры при помощи АЦП и сохранение полученных
Исправила

2023-04-29 12:52 UTC, Kseelina commented on Kursovow.adoc
> +- 0: Таймер TIM1 отключены +
Исправила

2023-04-29 12:53 UTC, Kseelina commented on Kursovow.adoc
>  Бит 4 DIR: Направление
Исправила

2023-04-29 13:01 UTC, Kseelina commented on Kursovow.adoc
> +- *1: прерывистое режим инжектированных каналов включены*
Исправила

2023-04-29 13:01 UTC, Kseelina commented on Kursovow.adoc
> +- 0: прерывистое режим инжектированных каналов отключены
Исправила

2023-04-29 13:02 UTC, Kseelina commented on Kursovow.adoc
> +. Измерение температуры при помощи АЦП и складывание полученных
Исправила

2023-04-29 13:02 UTC, Kseelina commented on Kursovow.adoc
> +- 0: часы TIM1 отключены +
Исправила

2023-04-29 13:02 UTC, Kseelina commented on Kursovow.adoc
> +- *1: часы TIM1 включены* +
Исправила

2023-04-29 13:02 UTC, Kseelina commented on Kursovow.adoc
> +- *0: Счетчик используется в качестве счетчика*
Исправила

2023-04-29 13:02 UTC, Kseelina commented on Kursovow.adoc
> +- 1: Счетчик используется как обратный счетчик +
Исправила

2023-04-29 13:03 UTC, Kseelina commented on Kursovow.adoc
> +- 0: Захват отключен
Исправила

2023-04-29 13:05 UTC, lamer0k commented on Kursovow.adoc
> +- *1: часы TIM1 включены* +
включены - включен в двух местах.

2023-04-29 13:07 UTC, lamer0k commented on Kursovow.adoc
> +- 0: Захват отключен
CC4 настроен как выход - настроен в режим сравнения.

2023-05-01 17:14 UTC, lamer0k commented on Kursovow.adoc
> +IDataSource o-- IMeasureParameter
Кто наследует IDataSource? IDataSource для чего нужен?  Это источник данных - считай кода АЦП, или например кода частоты флоуметра... Т.е. его должен наследовать ADC или там FlowmeterSensor.

2023-05-01 17:14 UTC, lamer0k commented on Kursovow.adoc
> +IDataSource o-- PWM
IDataSource не может ничего агрегировать (такой прозрачный ромбик) - это интерфейс. у него только методы.

2023-05-01 17:15 UTC, lamer0k commented on Kursovow.adoc
> +TemperatureTask o-- Temperature
Температура должна наследовать IMeasureParameter

2023-05-01 17:16 UTC, lamer0k commented on Kursovow.adoc
> +StartConversation():void
Удали пока методы, они путают.

2023-05-01 17:16 UTC, lamer0k commented on Kursovow.adoc
> +  IMeasureParameter(int32_t code): float
Это как? - Температура должна наследовать IMeasureParameter

2023-05-01 17:17 UTC, lamer0k commented on Applications/DataTransfer/Modbus/Modbus.h
> +class Modbus
1. Удали из этой ветки весь код - для кода сделай новую ветку.
2. Не надо пока все подряд пихать, сделай все классы пустые.

2023-05-01 17:18 UTC, lamer0k commented on Kursovow.adoc
> +IMeasureParameter(int32_t code): float
WaterConsumtion должен наследовать IMeasureParameter

2023-05-01 17:20 UTC, lamer0k commented on Kursovow.adoc
> +GetData():void
Удали все методы.

2023-05-01 17:21 UTC, lamer0k commented on Kursovow.adoc
> +Calculated( float CurrentTemperature, float SetTemperature, float FlowRate): float
Удали пока все методы.

2023-05-01 17:21 UTC, lamer0k commented on Kursovow.adoc
> +Send():void
Удали пока все методы.

2023-05-01 17:21 UTC, lamer0k commented on Kursovow.adoc
> +   Calculated (int32_t code) float
Не надо сюда передвать код. просто Calculate() float

2023-05-01 17:24 UTC, lamer0k commented on Kursovow.adoc
> +FlowTask o-- WaterConsumtion
тоже самое FlowTask o-- IMeasureParameter

2023-05-01 17:30 UTC, lamer0k requested changes

2023-05-01 17:30 UTC, lamer0k commented on Kursovow.adoc
> +PWM o-- CurrentControler
Зачем?   Что вообще делает CurrentController? приавльно я понимаю, что он принимает решение отрубить ток или нет? 
Если так, то он должен быть композицей подрублен к CurrentPowerRegulationTask

2023-05-05 03:46 UTC, Kseelina commented on Kursovow.adoc
> +GetData():void
Исправлено

2023-05-05 03:47 UTC, Kseelina commented on Kursovow.adoc
> +  IMeasureParameter(int32_t code): float
Исправлено

2023-05-05 03:47 UTC, Kseelina commented on Kursovow.adoc
> +StartConversation():void
Исправлено

2023-05-05 03:51 UTC, Kseelina commented on Kursovow.adoc
> +IMeasureParameter(int32_t code): float
Исправлено

2023-05-05 03:54 UTC, Kseelina commented on Kursovow.adoc
> +Calculated( float CurrentTemperature, float SetTemperature, float FlowRate): float
Исправлено

2023-05-05 03:54 UTC, Kseelina commented on Kursovow.adoc
> +Send():void
Исправлено

2023-05-05 04:04 UTC, Kseelina commented on Kursovow.adoc
> +   Calculated (int32_t code) float
Исправлено

2023-05-05 04:16 UTC, Kseelina commented on Kursovow.adoc
> +TemperatureTask o-- Temperature
Исправлено

2023-05-05 04:16 UTC, Kseelina commented on Kursovow.adoc
> +FlowTask o-- WaterConsumtion
Исправлено

2023-05-05 12:09 UTC, Kseelina commented on Kursovow.adoc
> +PWM o-- CurrentControler
CurrentController рассчитывает мощность, подаваемую на элементы Пельтье., PWM уже рассчитывает сам CCR чтобы постоянно выдавать нужное напряжение на элементы Пельтье.
если же расхода воды с кране не будет, то CurrentController должен потихоньку уменьшать мощность доводя её до 0

2023-05-05 12:49 UTC, lamer0k approved these changes
Все хорошо

2023-05-05 12:49 UTC, merged