FlowMeter
Kseelina/POIP_Kersovow pull request #7
Opened 2023-05-13 12:17 UTC by Kseelina

2023-05-14 11:55 UTC, lamer0k commented on Kursovow.adoc
> +  - At: float
они должны быть const

2023-05-14 11:56 UTC, lamer0k commented on Kursovow.adoc
> +  + Start():void
Что делают Start и Stop и почему они публичные?

2023-05-14 12:14 UTC, lamer0k commented on Kursovow.adoc
> +  - numberTopsFronts: uint32_t
Что такое numberTopsFronts?  Количество фронтов?????? 
Надо понять как ты будешь измерять.
Есть два варианта

Давай подумаем сколько абстракций надо
1. Таймер - отвечает за захват значения.
2. Измеритель частоты
3. Измеритель расхода.
4. Компаратор расхода -  считай сузщность которая принимает решение по тому, расход норм или маленький.

Теперь кто кого вызвает?

1. Таймер срабатывает прерывание
2. В прерывании вызвается метод Измерителя частоты, для передачи ему значения в захвате
3. Измерить забирает значение и расчиытвает частоту
4. Измерить частоты оповещает Измеритель расхода, что частота посчитана, считай расход. 


1. У таймера срабатывает прерывание, он в прерывании оповещает скажем флоуметер, и передает сразу значение регистра ззахвата. Для этого можно использовать шаблон Подписчики, и в таком случае у измеритель частоты должен быть метод скажем OnCapture(uint32_t value). Если шаблон Подписчик классический, то этот метод должен наследоваться из интерфейса? скажем ICaptureSubscriber. Но можно использовать статический полиморфизм, и использовать утиную типизацию, передав ссылку на объект  Flowmeter через шаблон. Давай лучше сделаем через интерфейс ICaptureSubscriber, у которого будет метод OnCapture(uint32_t value)
2. Срабатывает таймер - вызваем OnCapture  у Измерителя частоты -  Измеритель частоты смотрит, есть ли прошлое значение, если есть, то он от текущего отимает прошлое и считает частоту, и в любом случае сохраняет текущее значение, как прошлое - вызыввает метод OnFrequencyMeasured(float frequency) у изхмерителя расхода - измеритель расхода расчитывает расход и сохраняет у себя - Задача расход, раз в секунду просыпается обращается к компаратору расхода, мол как там расход? - компаратор идет в расход через интерфейс IDataSource берет расход и сравнивает его с расходом - если что-то не так, то оповещает кого надо, что расход очень мал.

2023-05-14 12:15 UTC, lamer0k commented on Kursovow.adoc
> +используемую для выборки входного сигнала TIM3,
в 517 строке можно убрать про DMA.

2023-05-14 12:16 UTC, lamer0k requested changes
Пару замечаний по архитектуре для расхода.

2023-05-19 12:10 UTC, Kseelina commented on Kursovow.adoc
> +используемую для выборки входного сигнала TIM3,
Исправлено

2023-05-19 12:10 UTC, Kseelina commented on Kursovow.adoc
> +  - At: float
Исправлено

2023-05-19 15:37 UTC, Kseelina commented on Kursovow.adoc
> +  - numberTopsFronts: uint32_t
Исправлено

2023-05-19 15:38 UTC, Kseelina commented on Kursovow.adoc
> +  + Start():void
Исправлено

2023-05-20 04:57 UTC, merged